### ISSUE TITLE
Error in clean function

### ISSUE THREAD

**Issue by apeterseil** [pmaletic/KYuK#1]
Hi,

when calling the clean function I am getting the error

Error in set(df, i = which(is.na(df[[j]])), j = j, value = 0) : 
  could not find function "set"

Maybe set is in some package that is not loaded automatically?

**Comment by pmaletic** [comment]
Hi thanks for the test. It was dependenci to the data.table package. I put it in the list in DESCRIPTION file and hope that is enough. Also I found one additional minor issue in the function and fixed it.
