### ISSUE TITLE
Naming and R Check Warning

### ISSUE THREAD

**Issue by apeterseil** [pmaletic/KYuK#2]
Hi,

as small issue I came across. We should use simple names which describe what the function does. 
E.g. normalize, standardize, etc.
The ending in _kyuc is redundant, as it is the package name anyways.

Furthermore, the documentation does not pass the check. This needs to be fixed.

Best,
Andreas

**Comment by JosephSpejbl** [comment]
Hello,
I changed names of the functions and their documentations. Now I cannot see any warning related to them. In case of any problem please notice me and I will improve it as soon as posible.

Best regards
Filip
